(function(global){
  'use strict';
  var busy=false;
  function shuffle(values){values=values.slice();for(var i=values.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),x=values[i];values[i]=values[j];values[j]=x;}return values;}
  function valid(folder){return (folder&&Array.isArray(folder.presets)?folder.presets:[]).filter(function(preset){return preset&&!preset.isFolder&&!Array.isArray(preset.presets);});}
  function picker(folder){var presets=valid(folder),ids=presets.map(function(preset){return preset.id;});if(!presets.length)throw new Error('This Random Preset folder is empty. Save selections into it first.');if(folder.shuffle===false){var index=Math.max(0,Number(folder.sequenceIndex)||0)%presets.length;return{preset:presets[index],bag:[],last:folder.lastPickedPresetId||'',sequenceIndex:(index+1)%presets.length};}var bag=(folder.shuffleBag||[]).filter(function(id,index,list){return ids.indexOf(id)>=0&&list.indexOf(id)===index;});if(!bag.length){bag=shuffle(ids);if(bag.length>1&&bag[0]===folder.lastPickedPresetId){var swap=1+Math.floor(Math.random()*(bag.length-1)),first=bag[0];bag[0]=bag[swap];bag[swap]=first;}}var picked=bag.shift(),preset=presets.filter(function(item){return item.id===picked;})[0]||presets[0];return{preset:preset,bag:bag,last:preset.id,sequenceIndex:Number(folder.sequenceIndex)||0};}
  function commit(folderId,state){if(!global.PremiereBindStorage)return Promise.resolve();return global.PremiereBindStorage.update(function(library){var profile=(library.profiles||[]).filter(function(item){return item.id===library.activeProfileId;})[0]||library.profiles[0],folder=(profile&&profile.presets||[]).filter(function(item){return item.id===folderId&&(item.isFolder||Array.isArray(item.presets));})[0];if(folder){folder.shuffleBag=state.bag.slice();folder.lastPickedPresetId=state.last;folder.sequenceIndex=state.sequenceIndex;}return library;}).then(function(library){global.dispatchEvent(new CustomEvent('premierebind:folders-changed',{detail:library}));return library;});}
  function insert(folder,options){if(busy)return Promise.reject(new Error('An insertion is already running.'));if(!global.PremiereBindInsertSelection||!global.PremiereBindBridge)return Promise.reject(new Error('Random Presets insertion service did not load.'));valid(folder);busy=true;options=options||{};return global.PremiereBindBridge.resolveInsertionTargets(options).then(function(targets){var working={shuffle:folder.shuffle,shuffleBag:(folder.shuffleBag||[]).slice(),lastPickedPresetId:folder.lastPickedPresetId||'',sequenceIndex:Number(folder.sequenceIndex)||0,presets:valid(folder)},results=[],names=[],chain=Promise.resolve();targets.times.forEach(function(seconds){chain=chain.then(function(){var choice=picker(working);working.shuffleBag=choice.bag;working.lastPickedPresetId=choice.last;working.sequenceIndex=choice.sequenceIndex;names.push(choice.preset.title||'Saved selection');return global.PremiereBindInsertSelection.insert(choice.preset,{mode:targets.mode,resolvedTargets:{mode:targets.mode,times:[seconds],count:1,snapHover:targets.snapHover===true},playSnap:null}).then(function(result){results.push(result);return commit(folder.id,choice);});});});return chain.then(function(){var failures=[];results.forEach(function(result){failures=failures.concat(result.transitionFailures||[]);});return{count:results.reduce(function(total,result){return total+Number(result.count||0);},0),targetCount:targets.count,mode:targets.mode,results:results,transitionFailures:failures,pickedNames:names};});}).then(function(result){busy=false;return result;},function(error){busy=false;throw error;});}
  global.PremiereBindFolderPresets={valid:valid,pick:picker,insert:insert};
})(window);
