(function (global) {
  'use strict';
  function isFolder(item){return Boolean(item&&(item.isFolder||Array.isArray(item.presets)));}
  function activeProfile(library){if(!library||!Array.isArray(library.profiles))return null;return library.profiles.filter(function(profile){return profile.id===library.activeProfileId;})[0]||library.profiles[0]||null;}
  function clipItems(preset){var result=[];(preset&&preset.children||[]).forEach(function(category){(category.items||[]).forEach(function(item){result.push(item);});});return result;}
  function durationSeconds(preset){var maximum=0;clipItems(preset).forEach(function(item){maximum=Math.max(maximum,(Number(item.relativeStart)||0)+(Number(item.duration)||0));});return maximum;}
  function formatDuration(seconds){seconds=Math.max(0,Math.round(Number(seconds)||0));var minutes=Math.floor(seconds/60),remaining=seconds%60;return (minutes<10?'0':'')+minutes+':'+(remaining<10?'0':'')+remaining;}
  function visualType(preset){if(preset&&preset.assetType==='true-nest')return 'nest';var categories=(preset&&preset.children||[]).filter(function(category){return category&&category.items&&category.items.length;}).map(function(category){return String(category.category||'').toLowerCase();});if(categories.length===1&&categories[0]==='audio')return 'audio';if(categories.indexOf('video clips')>=0)return 'video';if(categories.indexOf('images')>=0)return 'image';if(categories.indexOf('adjustment layers')>=0)return 'adjustment';return categories.length===1&&categories[0]==='other media'?'other':'mixed';}
  function preview(clips){var images=/\.(avif|bmp|gif|jpe?g|png|webp)$/i,videos=/\.(avi|m4v|mov|mp4|mpeg|mpg|webm)$/i;for(var i=0;i<clips.length;i++){var item=clips[i],path=String(item&&item.source&&item.source.mediaPath||'');if(!path)continue;if(videos.test(path))return{kind:'video',path:path,start:Number(item.inPoint)||0,end:Number(item.outPoint)||((Number(item.inPoint)||0)+(Number(item.duration)||0))};if(images.test(path))return{kind:'image',path:path,start:0,end:0};}return null;}
  function model(preset,folder){var clips=clipItems(preset),count=Number(preset.clipCount)||clips.length,seconds=durationSeconds(preset);return {id:String(preset.id||''),name:String(preset.title||'Saved selection'),folder:folder?String(folder.title||''):'',folderId:folder?String(folder.id||''):'',duration:formatDuration(seconds),durationSeconds:seconds,type:preset.assetType==='true-nest'?'True Nest':'Selection',shortcut:String(preset.shortcut||''),clips:count+' clip'+(count===1?'':'s'),clipCount:count,art:visualType(preset),word:'',capturedAt:String(preset.capturedAt||''),preview:preview(clips),preset:preset};}
  function collect(library,folderId){var profile=activeProfile(library);if(!profile)return[];var output=[];(profile.presets||[]).forEach(function(item){if(isFolder(item)){if(!folderId||item.id===folderId)(item.presets||[]).forEach(function(preset){if(!isFolder(preset))output.push(model(preset,item));});}else if(!folderId)output.push(model(item,null));});return output;}
  function visible(library,folderId,query,sort){var needle=String(query||'').trim().toLowerCase();var items=collect(library,folderId).filter(function(item){return !needle||item.name.toLowerCase().indexOf(needle)>=0||item.folder.toLowerCase().indexOf(needle)>=0;});if(sort==='name')items.sort(function(a,b){return a.name.localeCompare(b.name);});else items.sort(function(a,b){return (Date.parse(b.capturedAt)||0)-(Date.parse(a.capturedAt)||0);});return items;}
  function find(library,id){var match=null;collect(library,'').some(function(item){if(item.id===String(id)){match=item;return true;}return false;});return match;}
  function findFolder(library,id){var profile=activeProfile(library),match=null;(profile&&profile.presets||[]).some(function(item){if(isFolder(item)&&item.id===String(id)){match=item;return true;}return false;});return match;}
  global.PremiereBindLibraryView={activeProfile:activeProfile,collect:collect,visible:visible,find:find,findFolder:findFolder,formatDuration:formatDuration};
})(window);
