(function(global){'use strict';
function fail(message){throw new Error(message);}function storage(){if(!global.PremiereBindStorage)fail('Storage unavailable.');return global.PremiereBindStorage;}function isFolder(x){return x&&(x.isFolder||Array.isArray(x.presets));}function find(library,id){var p=library.profiles.filter(function(x){return x.id===library.activeProfileId;})[0]||library.profiles[0],found=null;(p&&p.presets||[]).some(function(x){if(!isFolder(x)&&x.id===id){found=x;return true;}if(isFolder(x))(x.presets||[]).some(function(y){if(y.id===id){found=y;return true;}return false;});return Boolean(found);});return found;}
function update(id,fn){return storage().update(function(l){var p=find(l,id);if(!p)fail('Saved selection not found.');fn(p);return l;}).then(function(l){global.dispatchEvent(new CustomEvent('premierebind:randomizers-changed',{detail:l}));return l;});}
function category(p,index){var c=(p.children||[])[Number(index)];if(!c)fail('Media category not found.');if(!Array.isArray(c.randomizerGroups))c.randomizerGroups=[];return c;}
function groupCount(p){var count=(p.pendingRandomizerGroups||[]).length;(p.children||[]).forEach(function(c){count+=(c.randomizerGroups||[]).length;});return count;}
function makeGroup(p){return{id:'randomizer-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),name:'Randomizer '+(groupCount(p)+1),targetTrack:'Smart',smartTargetDefaultApplied:true,shuffleBag:[],lastPickedItemId:''};}
function add(id,index){return update(id,function(p){var c=category(p,index);c.randomizerGroups.push(makeGroup(p));});}
function addEmpty(id){return update(id,function(p){if(!Array.isArray(p.pendingRandomizerGroups))p.pendingRandomizerGroups=[];p.pendingRandomizerGroups.push(makeGroup(p));});}
function patch(id,index,groupId,values){return update(id,function(p){var list=index==='pending'?(p.pendingRandomizerGroups||(p.pendingRandomizerGroups=[])):category(p,index).randomizerGroups,g=list.filter(function(x){return x.id===groupId;})[0];if(!g)fail('Randomizer not found.');if(values.name)g.name=String(values.name).trim().slice(0,50);if(values.targetTrack)g.targetTrack=String(values.targetTrack);if(index!=='pending')(category(p,index).items||[]).forEach(function(item){if(item.randomizerGroupId===groupId){if(!item.source)item.source={};item.source.randomizerTargetTrack=String(g.targetTrack||'Smart');}});g.shuffleBag=[];g.lastPickedItemId='';});}
function remove(id,index,groupId){return update(id,function(p){if(index==='pending'){p.pendingRandomizerGroups=(p.pendingRandomizerGroups||[]).filter(function(x){return x.id!==groupId;});return;}var c=category(p,index);(c.items||[]).forEach(function(x){if(x.randomizerGroupId===groupId)x.randomizerGroupId='';});c.randomizerGroups=c.randomizerGroups.filter(function(x){return x.id!==groupId;});});}
function assign(id,index,itemId,groupId){return update(id,function(p){var c=category(p,index),item=(c.items||[]).filter(function(x){return x.id===itemId;})[0];if(!item)fail('Clip not found.');if(groupId&&!c.randomizerGroups.some(function(x){return x.id===groupId;})){var pending=(p.pendingRandomizerGroups||[]),group=pending.filter(function(x){return x.id===groupId;})[0];if(!group)fail('A Randomizer can contain only one media type.');p.pendingRandomizerGroups=pending.filter(function(x){return x.id!==groupId;});c.randomizerGroups.push(group);}item.randomizerGroupId=groupId||'';if(!item.source)item.source={};if(groupId){var assigned=c.randomizerGroups.filter(function(g){return g.id===groupId;})[0];item.source.randomizerTargetTrack=String(assigned&&assigned.targetTrack||'Smart');}else delete item.source.randomizerTargetTrack;c.randomizerGroups.forEach(function(g){g.shuffleBag=[];g.lastPickedItemId='';});});}
function commitChoices(id,choices){return update(id,function(p){(choices||[]).forEach(function(choice){var c=category(p,choice.categoryIndex),g=c.randomizerGroups.filter(function(x){return x.id===choice.groupId;})[0];if(g){g.shuffleBag=choice.nextBag||[];g.lastPickedItemId=choice.selectedItemId||'';}});});}
global.PremiereBindRandomizers={add:add,addEmpty:addEmpty,patch:patch,remove:remove,assign:assign,commitChoices:commitChoices};
})(window);
